// <auto-generated />
using Bulky.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bulky.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20251108044438_Addproductableandseedproductodatabse")]
    partial class Addproductableandseedproductodatabse
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BulkyWeb.Models.Catogery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("catogeries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "SciFi"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "History"
                        });
                });

            modelBuilder.Entity("BulkyWeb.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "F. Scott Fitzgerald",
                            Description = "A classic novel by F. Scott Fitzgerald exploring themes of wealth, love, and the American dream.",
                            ISBN = "9780743273565",
                            ListPrice = 199.0,
                            Price = 189.0,
                            Price100 = 169.0,
                            Price50 = 179.0,
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            Id = 2,
                            Author = "James Clear",
                            Description = "A guide to building good habits and breaking bad ones with small incremental changes.",
                            ISBN = "9780735211292",
                            ListPrice = 499.0,
                            Price = 479.0,
                            Price100 = 439.0,
                            Price50 = 459.0,
                            Title = "Atomic Habits"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Robert C. Martin",
                            Description = "A handbook of agile software craftsmanship with practical advice for writing cleaner code.",
                            ISBN = "9780132350884",
                            ListPrice = 799.0,
                            Price = 769.0,
                            Price100 = 699.0,
                            Price50 = 729.0,
                            Title = "Clean Code"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Andrew Hunt and David Thomas",
                            Description = "Classic guide to software engineering best practices and mindset for developers.",
                            ISBN = "9780201616224",
                            ListPrice = 699.0,
                            Price = 669.0,
                            Price100 = 599.0,
                            Price50 = 639.0,
                            Title = "The Pragmatic Programmer"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Cal Newport",
                            Description = "A book on focused success in a distracted world, emphasizing deep concentration and productivity.",
                            ISBN = "9781455586691",
                            ListPrice = 399.0,
                            Price = 379.0,
                            Price100 = 339.0,
                            Price50 = 359.0,
                            Title = "Deep Work"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
